- name: Download jenkins repo
  get_url: url=http://pkg.jenkins-ci.org/redhat/jenkins.repo dest=/etc/yum.repos.d/jenkins.repo
  sudo: yes

- name: RPM Import key
  command: rpm --import http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
  sudo: yes

- name: Install package java
  yum: name=java-1.7.0-openjdk state=latest
  sudo: yes

- name: Install package jenkins
  yum: name=jenkins state=latest
  sudo: yes

- name: Setup Jenkins prefix to /jenkins
  lineinfile: dest=/etc/sysconfig/jenkins regexp=^JENKINS_ARGS= line=JENKINS_ARGS="--prefix=/jenkins"
  sudo: yes

- name: Setup HTTP reverse proxy
  action: template src=apache.conf dest=/etc/httpd/conf.d/jenkins.conf
  sudo: yes

- name: Start Jenkins
  service: name=jenkins state=started
  sudo: yes

- name: chkconfig on jenkins
  command: chkconfig jenkins on
  sudo: yes

- name: Sleep, waiting for Jenkins to be ready to work
  command: sleep 30
