# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centOS-6.3-i386"
  config.vm.hostname = "jenkins-slave.dev"
  config.vm.network :private_network, ip: '192.168.33.30'

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "provisioning/jenkins-slave.yml"
    ansible.inventory_file = "provisioning/ansible_hosts"
    ansible.verbose = true;
  end
end
