#! /bin/bash
#

## Get the right home dir for sitespeed.io
PRG="$0"
progname=`basename "$0"`

# need this for relative symlinks
while [ -h "$PRG" ] ; do
ls=`ls -ld "$PRG"`
link=`expr "$ls" : '.*-> \(.*\)$'`
if expr "$link" : '/.*' > /dev/null; then
PRG="$link"
else
PRG=`dirname "$PRG"`"/$link"
fi
done

home=`dirname "$PRG"`/..

## This is the home of perfite
PERFITE_HOME=$(cd "$home" > /dev/null && pwd)
TEMPLATE_HOME=$PERFITE_HOME/cli/templates
## finished getting home

# ENV Options #
source $PERFITE_HOME/cli/functions/variables.sh

function new() {
  local name=$2
  if [[ $name == '' ]]; then
    echo "Missing name argument: $0 new [name]"
    exit 1
  fi

  local jobname=$(echo "$PERFITE_JENKINS_JOB_PATTERN" | sed "s/\$name/$name/g")
  local graphitePrefix=$(echo "$GRAPHITE_PREFIX" | sed "s/\$name/$name/g")
  local gitRepo=$(echo "$GIT_REPOSITORY_PATTERN" | sed "s/\$name/$name/g")

  echo "... Generating $name repository ..."
  cp -r $TEMPLATE_HOME/repo $name
  cat $TEMPLATE_HOME/config.xml \
    | sed "s/\$name/$name/g" \
    | sed "s/\$GRAPHITE_PREFIX/$graphitePrefix/g" \
    | sed "s/\$GRAPHITE_SERVER/$GRAPHITE_SERVER/g" \
    | sed "s/\$GRAPHITE_PORT/$GRAPHITE_PORT/g" \
    | sed "s/\$GIT_REPOSITORY/$gitRepo/g" \
    > $name/config.xml

  cat $TEMPLATE_HOME/repo/dashboard/dashboard.js | sed "s/\$name/$name/g" > $name/dashboard/dashboard.js
  echo "... Repo created at ./$name .."

  cd ./$name
  git init
  git remote add origin $(echo $gitRepo | tr -d '\\')

  echo """

Repository ready, you should push the repository to the remote git repo with:

    $ cd ./$name
    $ git add .
    $ git commit -m 'First commit for $name'
    $ git push -u origin master

You can setup the default CI configuration with:

    $ cd ./$name
    $ perfite ci
"""
}

function ci() {
  local name=$2
  if [[ $name == '' ]]; then
    name=`basename $(pwd)`
  fi

  local jobname=$(echo "$PERFITE_JENKINS_JOB_PATTERN" | sed "s/\$name/$name/g")

  if [[ ! -e config.xml ]]; then
    echo "Missing config.xml. Please cd into the monitoring repository before running the command."
    exit 1
  fi

  if [[ ! -e urls.txt ]]; then
    echo "Missing urls.txt. Please cd into the monitoring repository before running the command."
    exit 1
  fi

  echo "... Creating / Updating $jobname job on $PERFITE_JENKINS_URL ..."
  local status=$(curl -s $PERFITE_JENKINS_URL/job/$jobname/config.xml -I | head -n 1 |cut -d$' ' -f2)

  local toCreate=false
  if [[ $status == '404' ]]; then
    toCreate='true'
  fi

  if [[ $toCreate == 'true' ]]; then
    curl $JENKINS_CURL_OPTIONS -H "Content-Type: text/xml" -s --data "@config.xml" "$PERFITE_JENKINS_URL/createItem?name=$jobname"
    echo "Job created: $PERFITE_JENKINS_URL/job/$jobname/"
  else
    echo "Job exists: $PERFITE_JENKINS_URL/job/$jobname/. Updating $PERFITE_JENKINS_URL/job/$jobname/config.xml"
    curl $JENKINS_CURL_OPTIONS -H "Content-Type: text/xml" -s --data "@config.xml" "$PERFITE_JENKINS_URL/job/$jobname/config.xml"
    echo "Config updated: $PERFITE_JENKINS_URL/job/$jobname/config.xml"
  fi
}

#*******************************************************
# Help function, call it to print all different usages.
#
#*******************************************************
function help() {
cat << EOF
usage: $0 options

Blah blah blah

COMMANDS:
   new - Scaffold out a new monitoring repo from a predefined template
   ci  - Setup jenkins job for the current repo

EOF
}

# test for a valid arg and execute it if so; otherwise show the help
if [ "$1" != "" ]; then
    wl=(new ci help)
    for i in "${wl[@]}"
    do
        if [ "$i" == "$1" ]
        then
            $1 $@
            exit 0
        fi
    done
fi

help
exit 0
