---

- name: Install Nodejs
  yum: "name={{ item }} state=present"
  with_items:
    - nodejs
    - git


- name: Create node user
  user: name=node state=present


- name: Create log directory
  file: path=/var/log/statsd owner=node group=node state=directory


- name: Install statsd from GitHub
  git: repo=https://github.com/etsy/statsd.git dest=/opt/statsd update=no version=v0.6.0


- name: Configure statsd
  template: src=opt/statsd/local_config.js.j2 dest=/opt/statsd/local_config.js owner=node group=node mode=0444


- name: Get directory permissions
  stat: path=/opt/statsd
  register: permissions


- name: Set file permissions
  command: /bin/chown -R node:node /opt/statsd
  when: permissions.stat.pw_name == 'root'


- name: Create statsd init.d script
  template: src=etc/init.d/statsd.j2 dest=/etc/init.d/statsd owner=root group=root mode=0755


- name: Start statsd 
  service: name=statsd state=running enabled=yes
