Vagrant.configure("2") do |config|

  config.vm.box = "centos63.minmal"
  config.vm.hostname = "graphite.dev"

  config.vm.synced_folder "ansible-graphite/", "/ansible"

  config.vm.network :private_network, ip: "192.168.33.33"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 2003, host: 2003
  config.vm.network "forwarded_port", guest: 8125, host: 8125, protocol: 'udp'

  config.vm.provision "shell", path: "shell_graphite_install.sh"

end
