# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos63.minmal"
  config.vm.hostname = "jenkins.dev"

  config.vm.network "forwarded_port", guest: 8080, host: 8082
  config.vm.network :private_network, ip: "192.168.33.11"
  # config.vm.network :public_network

  # config.vm.provision :ansible do |ansible|
  #   ansible.playbook = "provisioning/jenkins.yml"
  #   ansible.verbose = true;
  # end

  config.vm.provision "shell", path: "install_jenkins.sh"
end
