
- name: Install phantomjs globally via npm
  shell: npm install phantomjs -g
  sudo: yes

- name: Ensure phantomjs init.d script
  template: src=phantomjs-init.d.j2 dest=/etc/init.d/phantomjs mode=0755
  sudo: yes

- name: Start Phantomjs
  service: name=phantomjs pattern="phantomjs --webdriver=9134" state=started enabled=yes
  sudo: yes

