- name: Install Jenkins plugin
  get_url: url=http://localhost:8080/jnlpJars/jenkins-cli.jar dest=/tmp/jenkins-cli.jar

- name: Install Jenkins plugin
  command: java -jar jenkins-cli.jar -s http://localhost:8080 install-plugin tap parameterized-trigger -restart chdir=/tmp

- name: Connect node, copy template XML
  template: src=slave.xml.j2 dest=/tmp/slave.xml

- name: Connect node, copy template script
  template: src=create-node.sh.j2 dest=/tmp/create-node.sh

- name: Connect node, run template script
  command: sh /tmp/create-node.sh

