---

- name: Install Graphite Dependencies
  yum: "name={{ item }} state=present"
  with_items:
    - sqlite
    - bitmap 
    - bitmap-fonts
    - python-sqlite2
    - pycairo


- name: Create PIP requirements file 
  copy: src=opt/graphite/requirements.txt dest=/tmp/requirements.txt

- name: Install Graphite from PIP
  pip: requirements=/tmp/requirements.txt
  environment:
    PYTHONPATH: "/opt/graphite/lib:/opt/graphite/webapp"


- name: Configure carbon cache
  template: src=opt/graphite/conf/carbon.conf.j2 dest=/opt/graphite/conf/carbon.conf mode=0644


- name: Configure carbon storage schema
  template: src=opt/graphite/conf/storage-schemas.conf.j2 dest=/opt/graphite/conf/storage-schemas.conf mode=0644


- name: Configure carbon storage aggregation
  template: src=opt/graphite/conf/storage-aggregation.conf.j2 dest=/opt/graphite/conf/storage-aggregation.conf mode=0644


- name: Configure carbon init.d script
  copy: src=etc/init.d/carbon-cache dest=/etc/init.d/carbon-cache


- name: Generate random secret key
  shell: tr -dc A-Za-z0-9_ < /dev/urandom | head -c 64; echo creates=/opt/graphite/webapp/graphite/local_settings.py
  register: SECRET_KEY


- name: Configure Graphite webapp
  template: src=opt/graphite/webapp/graphite/local_settings.py.j2 dest=/opt/graphite/webapp/graphite/local_settings.py mode=0644
  when: SECRET_KEY.skipped is not defined
  notify:
    - reload httpd


- name: Configure graphite.wsgi
  copy: src=opt/graphite/conf/graphite.wsgi dest=/opt/graphite/conf/graphite.wsgi mode=0644
  notify:
    - reload httpd


- name: Setup sqlite DB
  command: /usr/bin/python manage.py syncdb --noinput chdir=/opt/graphite/webapp/graphite creates=/opt/graphite/storage/graphite.db


- name: Get directory permissions
  stat: path=/opt/graphite
  register: permissions


- name: Set file permissions
  command: /bin/chown -R apache:apache /opt/graphite
  when: permissions.stat.pw_name == 'root'


- name: Start apache httpd
  service: name=httpd state=running enabled=yes


- name: Start carbon cache
  service: name=carbon-cache state=running enabled=yes

