# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos63.minmal"
  config.vm.hostname = "jenkins-slave.dev"
  config.vm.network :private_network, ip: '192.168.33.30'

  #config.vm.provision :ansible do |ansible|
  #  ansible.playbook = "provisioning/jenkins-slave.yml";
  #end

  config.vm.provision "shell", path: "install_jenkins_slave.sh"
end
